// <auto-generated />
using ExamWeb_PhamHuynhAnh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_PhamHuynhAnh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611010710_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_PhamHuynhAnh.Models.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DienVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Phims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DienVien = "Trần Nghĩa",
                            GiaVe = 75000.0,
                            ThoiLuong = 117,
                            TrongNuoc = true,
                            TuaDe = "Mắt Biếc"
                        },
                        new
                        {
                            Id = 2,
                            DienVien = "Robert Downey Jr.",
                            GiaVe = 120000.0,
                            ThoiLuong = 181,
                            TrongNuoc = false,
                            TuaDe = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 3,
                            DienVien = "Song Kang-ho",
                            GiaVe = 95000.0,
                            ThoiLuong = 132,
                            TrongNuoc = false,
                            TuaDe = "Parasite"
                        },
                        new
                        {
                            Id = 4,
                            DienVien = "Trấn Thành",
                            GiaVe = 80000.0,
                            ThoiLuong = 128,
                            TrongNuoc = true,
                            TuaDe = "Bố Già"
                        },
                        new
                        {
                            Id = 5,
                            DienVien = "Christian Bale",
                            GiaVe = 110000.0,
                            ThoiLuong = 152,
                            TrongNuoc = false,
                            TuaDe = "The Dark Knight"
                        },
                        new
                        {
                            Id = 6,
                            DienVien = "Avin Lu",
                            GiaVe = 70000.0,
                            ThoiLuong = 136,
                            TrongNuoc = true,
                            TuaDe = "Em và Trịnh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
