// <auto-generated />
using ExamWeb_LeThe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_LeThenguyen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_LeTheNguyen.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaSi = "Sobin HoangSon",
                            Giaban = 75000.0,
                            ThoiLuong = 500,
                            TrongNuoc = true,
                            TuaDe = "Neu ngay ay"
                        },
                        new
                        {
                            Id = 2,
                            CaSi = "SonTungMTP",
                            GiaBan = 75000.0,
                            ThoiLuong = 500,
                            TrongNuoc = true,
                            TuaDe = "Lac Troi"
                        },
                        new
                        {
                            Id = 3,
                            CaSi = "Nguyen Tran trung Quan",
                            GiaBan = 75000.0,
                            ThoiLuong = 500,
                            TrongNuoc = true,
                            TuaDe = "Tu Tam"
                        
                        
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
